name: PHP

on: [pull_request]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Install dependencies
        run: composer dev

      - name: Validate against PSR-12
        run: composer lint

      - name: Run static analysis
        run: composer analyse
